version: '3.4'

services:
  bookdemo.web:
    ports:
      - "30000:80"
    image: ${DOCKER_REGISTRY-}bookdemoweb
    build:
      context: .
      dockerfile: DomainCentricDemo.Web/Dockerfile
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "http://+:80"
      "ConnectionStrings:DefaultConnection": "Server=host.docker.internal;Database=BookDbUsers;User Id=docker; Password=docker1234;Trusted_Connection=False;MultipleActiveResultSets=true; TrustServerCertificate=true"
      "BackendBaseUri": "http://bookdemo.api/"
      "WetherBaseUri": "http://weatherdemo.api/"
    depends_on:
      - bookdemo.api
      - weatherdemo.api

  weatherdemo.api:
    ports:
      - "30001:80"
    image: ${DOCKER_REGISTRY-}weatherdemoapi
    build:
      context: .
      dockerfile: DemoApi/Dockerfile
    environment:    
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "http://+:80"

  bookdemo.api:
    ports:
      - "30002:80"
    image: ${DOCKER_REGISTRY-}bookdemoapi
    build:
      context: .
      dockerfile: DomainCentricDemo.Api/Dockerfile
    environment:    
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "http://+:80"
      "ConnectionStrings:BookConnectionString": "Server=host.docker.internal;Database=BookDb;User Id=docker; Password=docker1234;Trusted_Connection=False;MultipleActiveResultSets=true; TrustServerCertificate=true"
 

