version: '3.4'

services:
  domaincentricdemo.web:
    image: ${DOCKER_REGISTRY-}domaincentricdemoweb
    build:
      context: .
      dockerfile: DomainCentricDemo.Web/Dockerfile

  domaincentricdemo.api:
    image: ${DOCKER_REGISTRY-}domaincentricdemoapi
    build:
      context: .
      dockerfile: DomainCentricDemo.Api/Dockerfile
        
  weatherdemo.api:
    image: ${DOCKER_REGISTRY-}weatherdemoapi
    build:
      context: .
      dockerfile: DemoApi/Dockerfile


