// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestApiDemo.Model;

#nullable disable

namespace RestApiDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("RestApiDemo.Model.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            Name = "Ralls, Kim"
                        },
                        new
                        {
                            AuthorId = 2,
                            Name = "Corets, Eva"
                        },
                        new
                        {
                            AuthorId = 3,
                            Name = "Randall, Cynthia"
                        },
                        new
                        {
                            AuthorId = 4,
                            Name = "Thurman, Paula"
                        });
                });

            modelBuilder.Entity("RestApiDemo.Model.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            Description = "A former architect battles an evil sorceress.",
                            Genre = "Fantasy",
                            Price = 14.95m,
                            PublishDate = new DateTime(2000, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Midnight Rain"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2,
                            Description = "After the collapse of a nanotechnology society, the youngsurvivors lay the foundation for a new society.",
                            Genre = "Fantasy",
                            Price = 12.95m,
                            PublishDate = new DateTime(2000, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Maeve Ascendant"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 2,
                            Description = "The two daughters of Maeve battle for control of England.",
                            Genre = "Fantasy",
                            Price = 12.95m,
                            PublishDate = new DateTime(2001, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Sundered Grail"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 3,
                            Description = "When Carla meets Paul at an ornithology conference, tempers fly.",
                            Genre = "Romance",
                            Price = 7.99m,
                            PublishDate = new DateTime(2000, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lover Birds"
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 4,
                            Description = "A deep sea diver finds true love 20,000 leagues beneath the sea.",
                            Genre = "Romance",
                            Price = 6.99m,
                            PublishDate = new DateTime(2000, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Splish Splash"
                        });
                });

            modelBuilder.Entity("RestApiDemo.Model.Book", b =>
                {
                    b.HasOne("RestApiDemo.Model.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
